package com.crud.crudassignmentsb.modal;

// default package
// Generated Oct 17, 2020 2:31:36 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Packages generated by hbm2java
 */
@Entity
@Table(name = "packages"
        , catalog = "crud_assignment"
)
public class Packages implements java.io.Serializable {


    private int pakId;
    private String pakName;
    private Byte pakStatus;
    private BigDecimal pakPrice;
    private String pakType;
    private String pakImg;
    private String pakDesc;

    public Packages() {
    }


    public Packages(int pakId) {
        this.pakId = pakId;
    }

    public Packages(int pakId, String pakName, Byte pakStatus, BigDecimal pakPrice, String pakType, String pakImg, String pakDesc) {
        this.pakId = pakId;
        this.pakName = pakName;
        this.pakStatus = pakStatus;
        this.pakPrice = pakPrice;
        this.pakType = pakType;
        this.pakImg = pakImg;
        this.pakDesc = pakDesc;
    }

    @Id

    @Column(name = "pak_id", unique = true, nullable = false)
    public int getPakId() {
        return this.pakId;
    }

    public void setPakId(int pakId) {
        this.pakId = pakId;
    }

    @Column(name = "pak_name", length = 50)
    public String getPakName() {
        return this.pakName;
    }

    public void setPakName(String pakName) {
        this.pakName = pakName;
    }

    @Column(name = "pak_status")
    public Byte getPakStatus() {
        return this.pakStatus;
    }

    public void setPakStatus(Byte pakStatus) {
        this.pakStatus = pakStatus;
    }

    @Column(name = "pak_price", precision = 10)
    public BigDecimal getPakPrice() {
        return this.pakPrice;
    }

    public void setPakPrice(BigDecimal pakPrice) {
        this.pakPrice = pakPrice;
    }

    @Column(name = "pak_type", length = 50)
    public String getPakType() {
        return this.pakType;
    }

    public void setPakType(String pakType) {
        this.pakType = pakType;
    }

    @Column(name = "pak_img")
    public String getPakImg() {
        return this.pakImg;
    }

    public void setPakImg(String pakImg) {
        this.pakImg = pakImg;
    }

    @Column(name = "pak_desc")
    public String getPakDesc() {
        return this.pakDesc;
    }

    public void setPakDesc(String pakDesc) {
        this.pakDesc = pakDesc;
    }


}



