package com.crud.crudassignmentsb.modal;

// default package
// Generated Oct 17, 2020 2:31:36 PM by Hibernate Tools 3.2.2.GA


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services"
        , catalog = "crud_assignment"
)
public class Services{


    private int serId;
    private String serName;
    private String serDesc;
    private String serStatus;
    private BigDecimal serOffer;
    private byte[] picByte;
    private String pacName;
    private String type;

    public Services() {
    }


    public Services(int serId, String serName) {
        this.serId = serId;
        this.serName = serName;
    }

    public Services(int serId, String serName, String serDesc, String serStatus, BigDecimal serOffer, byte[] picByte, String pacName, String type) {
        this.serId = serId;
        this.serName = serName;
        this.serDesc = serDesc;
        this.serStatus = serStatus;
        this.serOffer = serOffer;
        this.picByte = picByte;
        this.pacName = pacName;
        this.type = type;
    }

    @Id

    @Column(name = "ser_id", unique = true, nullable = false)
    public int getSerId() {
        return this.serId;
    }

    public void setSerId(int serId) {
        this.serId = serId;
    }

    @Column(name = "ser_name", nullable = false, length = 100)
    public String getSerName() {
        return this.serName;
    }

    public void setSerName(String serName) {
        this.serName = serName;
    }

    @Column(name = "ser_desc")
    public String getSerDesc() {
        return this.serDesc;
    }

    public void setSerDesc(String serDesc) {
        this.serDesc = serDesc;
    }

    @Column(name = "ser_status", length = 50)
    public String getSerStatus() {
        return this.serStatus;
    }

    public void setSerStatus(String serStatus) {
        this.serStatus = serStatus;
    }

    @Column(name = "ser_offer", precision = 20)
    public BigDecimal getSerOffer() {
        return this.serOffer;
    }

    public void setSerOffer(BigDecimal serOffer) {
        this.serOffer = serOffer;
    }

    @Column(name = "pic_byte")
    public byte[] getPicByte() {
        return this.picByte;
    }

    public void setPicByte(byte[] picByte) {
        this.picByte = picByte;
    }

    @Column(name = "pac_name", length = 10)
    public String getPacName() {
        return this.pacName;
    }

    public void setPacName(String pacName) {
        this.pacName = pacName;
    }

    @Column(name = "type")
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
}




